<%@ Page Language="VB" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<script runat="server">
  Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs)
    'set the label text to the current time
    myTimeLabel.Text = DateTime.Now.ToString()
  End Sub
</script>

<html xmlns="http://www.w3.org/1999/xhtml">
  <head runat="server">
    <title>Welcome to Build Your Own ASP.NET 3.5 Web Site!</title>
  </head>
  <body>
    <form id="form1" runat="server">
    <div>
      <p>Hello there!</p>
      <p>
        The time is now:
        <%-- Display the current date and time --%>
        <asp:Label ID="myTimeLabel" runat="server" />
      </p>
      <p>
        <%-- Declare the title as string and set it --%>
        <% Dim Title As String = "This is generated by a code render block."%>
        <%= Title %>
      </p>    
    </div>
    </form>
  </body>
</html>
